bin.includes = META-INF/,\
               OSGI-INF/customJMSProvider.xml,\
               .,\
               .settings/,\
               OSGI-INF/,\
               bin/,\
               lib/,\
               pom.xml,\
               .WebResources/,\
               target/
source.. = src/
javacTarget = 1.2
