<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://tns.tibco.com/bw/json/1691163651447" elementFormDefault="qualified" targetNamespace="http://tns.tibco.com/bw/json/1691163651447">
  <complexType name="ACIfeed-BoardingNowSchemaElementType">
    <sequence>
      <element maxOccurs="1" minOccurs="0" name="root">
        <complexType>
          <sequence>
            <element maxOccurs="unbounded" minOccurs="0" name="flightList">
              <complexType>
                <sequence>
                  <element maxOccurs="1" minOccurs="0" name="airlineCode" type="string"/>
                  <element maxOccurs="1" minOccurs="0" name="flightNumber" type="string"/>
                  <element maxOccurs="1" minOccurs="0" name="flightDate" type="string"/>
                  <element maxOccurs="1" minOccurs="0" name="shipChanges" type="string"/>
                  <element maxOccurs="1" minOccurs="0" name="totalLegs" type="string"/>
                  <element maxOccurs="1" minOccurs="0" name="termCityCode" type="string"/>
                  <element maxOccurs="1" minOccurs="0" name="codeShareFlightNumber" type="string"/>
                  <element maxOccurs="1" minOccurs="0" name="lastSeqNumber" type="string"/>
                  <element maxOccurs="1" minOccurs="0" name="flightControlInd" type="string"/>
                  <element maxOccurs="1" minOccurs="0" name="aciTimestamp" type="string"/>
                  <element maxOccurs="unbounded" minOccurs="0" name="legList">
                    <complexType>
                      <sequence>
                        <element maxOccurs="1" minOccurs="0" name="cityIndex" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="cityCode" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="legIndicator" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="dateAdjusted" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="shipChangeNumber" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="equipmentCode" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="tailNumber" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="departureGate" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="etdTime" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="etdDate" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="stdDepTime" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="stdDepDate" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="boardingTime" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="boardingDate" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="boardingTimeAdj" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="boardingTimeChangeFactor" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="totalCompartments" type="string"/>
                        <element maxOccurs="unbounded" minOccurs="0" name="compartmentList">
                          <complexType>
                            <sequence>
                              <element maxOccurs="1" minOccurs="0" name="compartmentCode" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="totalSeats" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="totalUsableSeats" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="seatsLessHeld" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="seatsLessHeldStandby" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="totalAssignableSeats" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="totalChildren" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="totalInfants" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="totalBagsChecked" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="bagWeightLimits" type="string"/>
                            </sequence>
                          </complexType>
                        </element>
                      </sequence>
                    </complexType>
                  </element>
                </sequence>
              </complexType>
            </element>
            <element maxOccurs="unbounded" minOccurs="0" name="paxlist">
              <complexType>
                <sequence>
                  <element maxOccurs="1" minOccurs="0" name="recordLocator" type="string"/>
                  <element maxOccurs="1" minOccurs="0" name="numberInParty" type="string"/>
                  <element maxOccurs="1" minOccurs="0" name="nameItemsSurname" type="string"/>
                  <element maxOccurs="1" minOccurs="0" name="passengerName" type="string"/>
                  <element maxOccurs="1" minOccurs="0" name="passengerIndicator" type="string"/>
                  <element maxOccurs="1" minOccurs="0" name="passengerType" type="string"/>
                  <element maxOccurs="1" minOccurs="0" name="passengerStandbyCdLength" type="string"/>
                  <element maxOccurs="1" minOccurs="0" name="passengerIdNumber" type="string"/>
                  <element maxOccurs="unbounded" minOccurs="0" name="paxflight">
                    <complexType>
                      <sequence>
                        <element maxOccurs="1" minOccurs="0" name="airlineCode" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="flightNumber" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="flightDate" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="passengerIdNumber" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="boardCityIdxNum" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="seatsUnassigned" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="serviceClass" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="passengerInd" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="passengerInd2" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="splPassengerInd" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="thruCityIndex" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="finalDestinationInd" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="originalClassBooked" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="compartmentFlown" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="gradeChangeClass" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="transferToServiceClass" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="transferToFlightNumber" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="transferToFlightDate" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="transferToFlightAirlineCd" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="transferToFlightCityCd" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="transferFromFlightNumber" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="transferFromFlightDate" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="transferFromFlightAirlineCd" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="transferFromFlightCityCd" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="alternateFlightNumber" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="consolidatedFlightNumber" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="standbyOrdinalNumber" type="string"/>
                        <element maxOccurs="1" minOccurs="0" name="pax_attributes">
                          <complexType>
                            <sequence>
                              <element maxOccurs="1" minOccurs="0" name="apiComplete" type="string"/>
							  <element maxOccurs="1" minOccurs="0" name="isCheckedIn" type="string"/>
                            </sequence>
                          </complexType>
                        </element>
                        <element maxOccurs="unbounded" minOccurs="0" name="seat_list">
                          <complexType>
                            <sequence>
                              <element maxOccurs="1" minOccurs="0" name="cityIdxNumber" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="totalSeats" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="compartmentClassCd" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="seatType" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="seatNumber" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="boardingZone" type="string"/>
                            </sequence>
                          </complexType>
                        </element>
						<element maxOccurs="unbounded" minOccurs="0" name="bag_list">
                          <complexType>
                            <sequence>
                              <element maxOccurs="1" minOccurs="0" name="bagIndicator" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="bagCount" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="bagWeight" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="carryBagCount" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="carryBagWeight" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="bagTagRange" type="string"/>
							  <element maxOccurs="1" minOccurs="0" name="bagTagNumber" type="string"/>
							  <element maxOccurs="1" minOccurs="0" name="totalBagsInRange" type="string"/>
							  <element maxOccurs="1" minOccurs="0" name="bagSpareInd1" type="string"/>
                            </sequence>
                          </complexType>
                        </element>
                        <element maxOccurs="unbounded" minOccurs="0" name="fqtv_list">
                          <complexType>
                            <sequence>
                              <element maxOccurs="1" minOccurs="0" name="fqtvSurnameNumber" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="fqtvNameInitNumber" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="fqtvIndicator" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="fqtvNumber" type="string"/>
                            </sequence>
                          </complexType>
                        </element>
                        <element maxOccurs="unbounded" minOccurs="0" name="seq_nbr_list">
                          <complexType>
                            <sequence>
                              <element maxOccurs="1" minOccurs="0" name="sequenceNumber" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="passengerBoarded" type="string"/>
                            </sequence>
                          </complexType>
                        </element>
                        <element maxOccurs="unbounded" minOccurs="0" name="sec_prof_list">
                          <complexType>
                            <sequence>
                              <element maxOccurs="1" minOccurs="0" name="securityNameInitial" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="securityCategory" type="string"/>
                            </sequence>
                          </complexType>
                        </element>
                        <element maxOccurs="unbounded" minOccurs="0" name="misc_list">
                          <complexType>
                            <sequence>
                              <element maxOccurs="1" minOccurs="0" name="miscIndicator" type="string"/>
                            </sequence>
                          </complexType>
                        </element>
                        <element maxOccurs="unbounded" minOccurs="0" name="hist_list">
                          <complexType>
                            <sequence>
                              <element maxOccurs="1" minOccurs="0" name="agentCityAAA" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="agentInitials" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="agentDutyCode" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="interchangeTerminal" type="string"/>
                            </sequence>
                          </complexType>
                        </element>
                        <element maxOccurs="unbounded" minOccurs="0" name="trans_times_list">
                          <complexType>
                            <sequence>
                              <element maxOccurs="1" minOccurs="0" name="checkInTime" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="checkInDate" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="transferTime" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="transferDate" type="string"/>
                            </sequence>
                          </complexType>
                        </element>
                        <element maxOccurs="unbounded" minOccurs="0" name="fqtv_tier_list">
                          <complexType>
                            <sequence>
                              <element maxOccurs="1" minOccurs="0" name="paxInitial" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="tierLevel" type="string"/>
                              <element maxOccurs="1" minOccurs="0" name="customerLevel" type="string"/>
                            </sequence>
                          </complexType>
                        </element>
                      </sequence>
                    </complexType>
                  </element>
                </sequence>
              </complexType>
            </element>
          </sequence>
        </complexType>
      </element>
    </sequence>
  </complexType>
  <element name="ACIfeed-BoardingNowSchemaElement" type="tns:ACIfeed-BoardingNowSchemaElementType"/>
</schema>
