<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://tns.tibco.com/bw/json/1737609436928" elementFormDefault="qualified" targetNamespace="http://tns.tibco.com/bw/json/1737609436928">
  <complexType name="PreEquipChangeDataElementType">
    <sequence>
    	<element maxOccurs="1" minOccurs="0" name="DEST_CD"
    		type="string" />
    	<element maxOccurs="1" minOccurs="0" name="SEAT_SEQ"
    		type="integer" />
    	<element maxOccurs="1" minOccurs="0" name="FLT_NUM"
    		type="string" />
    	<element maxOccurs="1" minOccurs="0" name="V_END_DTMZ"
    		type="string" />
    	<element maxOccurs="1" minOccurs="0" name="RECLOC"
    		type="string" />
    	<element maxOccurs="1" minOccurs="0" name="SEAT_NUM"
    		type="string" />
    	<element name="LAST_NAME" type="string" minOccurs="0"
    		maxOccurs="1">
    	</element>
    	<element maxOccurs="1" minOccurs="0" name="V_BEG_DTMZ"
    		type="string" />
    	<element name="FIRST_NAME" type="string" minOccurs="0" maxOccurs="1"></element>
    	<element maxOccurs="1" minOccurs="0" name="PAX_CNT"
    		type="integer" />
    	<element maxOccurs="1" minOccurs="0" name="CREATION_DTZ"
    		type="string" />
    	<element maxOccurs="1" minOccurs="0" name="CARRIER_CD"
    		type="string" />
    	<element maxOccurs="1" minOccurs="0" name="DEP_KEY"
    		type="string" />
    	<element maxOccurs="1" minOccurs="0" name="DEP_DT"
    		type="string" />
    	<element maxOccurs="1" minOccurs="0" name="ORIG_CD"
    		type="string" />
    </sequence>
  </complexType>
  <element name="PreEquipChangeDataElement" type="tns:PreEquipChangeDataElementType"/>
  <complexType name="PreEquipChangeDataElementArrayType">
    <sequence>
      <element maxOccurs="unbounded" minOccurs="0" ref="tns:PreEquipChangeDataElement"/>
    </sequence>
  </complexType>
  <element name="PreEquipChangeDataElementArray" type="tns:PreEquipChangeDataElementArrayType"/>
</schema>
