<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/SeatsData" xmlns:tns="http://www.example.org/SeatsData" elementFormDefault="qualified">
<element  name="seatsDataElementType" >
        <complexType >
          <sequence>
          	<element maxOccurs="1" minOccurs="0" name="originalSeat"
          		type="string" />
          	<element maxOccurs="1" minOccurs="0" name="mismatchSeat"
          		type="string" />
          	<element name="firstName" type="string" minOccurs="0" maxOccurs="1"></element>
          	<element name="lastName" type="string" minOccurs="0" maxOccurs="1"></element>
          	<element name="FullName" type="string" minOccurs="0" maxOccurs="1"></element>
          	<element name="isMissmatched" type="boolean" minOccurs="0" maxOccurs="1"></element>
          </sequence>
        </complexType>
  </element>      
   

   <element name="seatsDataArray" >
   <complexType>
   <sequence>
   <element maxOccurs="unbounded" minOccurs="0" ref="tns:seatsDataElementType"/>
   </sequence>
   </complexType>
   </element>
</schema>