<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/seatDetails" xmlns:tns="http://www.example.org/seatDetails" elementFormDefault="qualified">


<element name="pnrDetails">
					<complexType>
						<sequence>
							<element name="PNR" type="string"  minOccurs="0" maxOccurs="1"/>
							<element name="SeatDetails" minOccurs="0" maxOccurs="unbounded">
								<complexType>
									<sequence>
										<element name="SeatNo" type="string" minOccurs="0" maxOccurs="1"/>
										<element name="PassengerName" type="string" minOccurs="0" maxOccurs="1"/>
									</sequence>
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>
</schema>