<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.tibco.bw</groupId>
  <artifactId>eda-operational-seats-affected.application.parent</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  <modules>
    <module>../../../../eda-osl-common-module/eda/eda-common-module</module> 
    <module>../eda-operational-seats-affected</module>
    <module>../com.tibco.custom.jms.provider</module>
    <module>../eda-operational-seats-affected.application</module>
  </modules>
  <distributionManagement>
    <repository>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <id>OSL-Components</id>
      <url>https://pkgs.dev.azure.com/copavsts/_packaging/OSL-Components/maven/v1</url>
    </repository>
  </distributionManagement>
  <repositories>
    <repository>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <id>OSL-Components</id>
      <url>https://pkgs.dev.azure.com/copavsts/_packaging/OSL-Components/maven/v1</url>
    </repository>
    <repository>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <id>maven-repo</id>
      <url>https://repo.maven.apache.org/maven2</url>
    </repository>
  </repositories>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-site-plugin</artifactId>
        <version>3.7.1</version>
      </plugin>
    </plugins>
  </build>
</project>
