scheduleAffectedSeats.Solace.resTopicPattarn=copa/INT/schedulechange/seataffected/missmatch/v1.0/cm
scheduleAffectedSeats.Solace.reqTopicPattarn=copa/INT/schedulechange/seataffected/initiated/v1.0/
scheduleAffectedSeats.Solace.reqQueueName=Q.EDA.SEAT.AFFECTED
scheduleAffectedSeats.Connections.HTTP.APIM_KEY=0e85894010ce4ceea0296c8cafc8f51b
scheduleAffectedSeats.Connections.HTTP.APIM_Channel=WEB